version: '2'
services:
  hawkular:
    image: "hawkular/hawkular-services:latest"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
    # volumes:
    #   - /tmp/opt/hawkular/server:/opt/data:Z
    environment:
      - CASSANDRA_NODES=hawkular-cassandra
      - ADMIN_TOKEN
      - HAWKULAR_AGENT_ENABLE=false
  hawkular-cassandra:
    image: cassandra:3.0.9
    environment:
      - CASSANDRA_START_RPC=true
  grafana:
    image: "hawkular/hawkular-grafana-datasource:latest"
    ports:
      - "3000:3000"
  bootstrap:
    image: "jotak/hawkular-grafana-bootstrap:latest"
    environment:
      - TENANT=put_your_tenant_here
      - DASHBOARDS=put_dashboard_file_names_here # only dashboards added from Dockerfile can be set here, see README
