version: '2'
services:
  hawkular:
    image: "hawkular/hawkular-services:0.40.1.Final"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
    # volumes:
    #   - /tmp/opt/hawkular/server:/opt/data:Z
    environment:
      - CASSANDRA_NODES=hawkular-cassandra
      - ADMIN_TOKEN
      - HAWKULAR_AGENT_ENABLE=true
  hawkular-cassandra:
    image: cassandra:3.0.9
    environment:
      - CASSANDRA_START_RPC=true
  grafana:
    image: "hawkular/hawkular-grafana-datasource:resolve-vars-annots"
    ports:
      - "3000:3000"
  bootstrap:
    image: "jotak/hawkular-grafana-bootstrap:latest"
    environment:
      - TENANT=hawkular
      - DASHBOARDS=hawkular-self
